# Workload configuration for the client

# Number of concurrent clients
num_clients: 5

# Requests per second per client
requests_per_second: 10

# Total duration of the test in seconds
duration_seconds: 60

# Server URL
server_url: "http://localhost:8080" 